### ISSUE TITLE
在插件没开的情况下，撤回的数据会变成"Msg has been recalled."

### ISSUE THREAD

**Issue by veryyoung** [veryyoung/DingDingUnrecalled#1]

**Comment by AaronGeist** [comment]
你好，我参考了你的code之后修正了这个问题，可以看下这里的code
https://github.com/AaronGeist/DingdingAntiMsgRecall/blob/master/app/src/main/java/aaron/geist/dingding/anti/msg/recall/AntiRecall.java

**Comment by veryyoung** [comment]
一直没空弄，主要是用的人太少了。

如果你做了那简直太好了，@AaronGeist 求 pr！！！
